### PR TITLE
Addition of Sama-COCO to external resources

### PR DESCRIPTION
**Pull request by EricZimmermann**
Adding Sama-COCO's reannotation of COCO2017 to the external resources of the page

### CODE REVIEW

**Comment by EricZimmermann** [comment]
@tylin please let me know if everything checks out.

**Comment by EricZimmermann** [comment]
Hello @pdollar @nightrome,

Is there any way we can get some support on this? We had followed up with Serge however tylin has not been available.

Thank you!

**Comment by nightrome** [comment]
Hi, Unfortunately I was only involved in the COCO-Stuff subset, so I am not responsible for this part.

**Comment by richardaecn** [comment]
Hi Eric,

I just approved your merge request. Thanks for adding sama-coco!

Best,
Yin

**Pull request merged**
